repos:
  - repo: local
    hooks:
      - id: gitleaks
        name: gitleaks
        entry: gitleaks detect --source=. --config=./gitleaks.toml
        language: system
        types: [text]
        pass_filenames: false
